 DROP TABLE IF EXISTS User;
  
CREATE TABLE User (
	`uid` VARCHAR(50) NOT NULL,
	`upw` VARCHAR(50) NULL DEFAULT NULL,
	`uname` VARCHAR(50) NULL DEFAULT NULL,
	`upoint` INT(11) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`googleid` VARCHAR(50) NULL DEFAULT NULL,
	`naverid` VARCHAR(50) NULL DEFAULT NULL,
	`nickname` VARCHAR(50) NULL DEFAULT NULL,
	`loginip` VARCHAR(50) NULL DEFAULT NULL,
	`lastlogin` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`uid`)
);

